services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb_server
    ports:
      - "8000:8000"   # Chroma REST API
    volumes:
      - ./chroma_data:/chroma/.chromadb   # Persist data
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE

  app_backend:
    image: asapp-backend
    build:
      context: ./ASAPP/backend
      dockerfile: Dockerfile
    container_name: asapp_backend
    ports:
      - "8088:8088"
    depends_on:
      - chromadb
    env_file:
      - .env
    environment:
      - CHROMA_URL=http://chromadb:8000
    #restart: always  #for production
    volumes:                  #for development
      - ./ASAPP/backend:/app  #hot reload
    restart: unless-stopped

  app_frontend:
    image: asapp-frontend
    build:
      context: ASAPP/frontend
      dockerfile: Dockerfile
      target: development
    container_name: asapp_frontend
    ports:
      - "3000:3000"
    depends_on:
      - app_backend
    environment:
      - REACT_APP_API_URL=http://localhost:8088
      - WATCHPACK_POLLING=true
    volumes:
      - ./ASAPP/frontend/src:/app/src
      - /app/node_modules
volumes:
  chroma_data:
