services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb_server
    ports:
      - "8000:8000"   # Chroma REST API
    volumes:
      - ./chroma_data:/chroma/.chromadb   # Persist data
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - asapp-network

  postgres:
    image: postgres:16-alpine  # Lighter image
    container_name: postgres_db_server
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-asapp_db}
      POSTGRES_INITDB_ARGS: "-c encoding=UTF8 --locale=C.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isReady -U ${DB_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - asapp-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_server
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - asapp-network


  app_backend:
    image: asapp-backend
    build:
      context: ./ASAPP/backend
      dockerfile: Dockerfile
    container_name: asapp_backend
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - CHROMA_URL=http://chromadb:8000
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    #restart: always  #for production
    volumes:                  #for development
      - ./ASAPP/backend:/app  #hot reload
    restart: unless-stopped
    networks:
      - asapp-network

  app_frontend:
    image: asapp-frontend
    build:
      context: ASAPP/frontend
      dockerfile: Dockerfile
      target: development
    container_name: asapp_frontend
    ports:
      - "3000:3000"
    depends_on:
      - app_backend
    environment:
      - REACT_APP_API_URL=http://localhost:8088
      - WATCHPACK_POLLING=true
    volumes:
      - ./ASAPP/frontend/src:/app/src
      - /app/node_modules
    networks:
      - asapp-network

volumes:
  chroma_data:
  postgres_data:
  pgadmin_data:

networks:
  asapp-network:
    driver: bridge
